version: "3"
services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./db-init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - "5432:5432"
