[Server]
Address = "localhost"
Port = "8080"

[Logger]
File = "./calendar.log"
Level = "INFO"

[Storage]
inMemory = false
SQLHost = "localhost"
SQLPort = "5432"
SQLDbase = "test"
SQLUser = "test"
SQLPass = "test"